export const TYPE_LOADING_FETCH_USERS = 'LOADING_FETCH_USERS';
export const TYPE_SUCCESS_FETCH_USERS = 'SUCCESS_FETCH_USERS';
export const TYPE_ERROR_FETCH_USERS = 'ERROR_FETCH_USERS';
export const TYPE_SELECTED_USER = 'SELECTED_USER';
export const TYPE_UNSELECTED_USER = 'UNSELECTED_USER';
export const TYPE_CHANGE_INPUT = 'CHANGE_INPUT';
