export const TYPE_FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const TYPE_FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const TYPE_FETCH_CATEGORIES_LOADING = 'FETCH_CATEGORIES_LOADING';
export const TYPE_SELECTED_CATEGORY = 'SELECTED_CATEGORY';
