export const TYPE_FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';
export const TYPE_FETCH_ROLES_FAILURE = 'FETCH_ROLES_FAILURE';
export const TYPE_FETCH_ROLES_LOADING = 'FETCH_ROLES_LOADING';
export const TYPE_SELECTED_ROLE = 'SELECTED_ROLE';
