export const TYPE_CHANGE_INPUT = 'CHANGE_INPUT';
export const TYPE_LOADING_CREATE_COURSE = 'LOADING_CREATE_COURSE';
export const TYPE_SUCCESS_CREATE_COURSE = 'SUCCESS_CREATE_COURSE';
export const TYPE_FAILURE_CREATE_COURSE = 'FAILURE_CREATE_COURSE';
