export const TYPE_LOADING_FETCH_COURSES = 'LOADING_FETCH_COURSES';
export const TYPE_SUCCESS_FETCH_COURSES = 'SUCCESS_FETCH_COURSES';
export const TYPE_ERROR_FETCH_COURSES = 'ERROR_FETCH_COURSES';
export const TYPE_DETAILS_COURSE = 'DETAILS_COURSE';
export const TYPE_DELETE_COURSE = 'DELETE_COURSE';
export const TYPE_EDIT_COURSE = 'EDIT_COURSE';
export const TYPE_CHANGE_INPUT = 'CHANGE_INPUT';
